### ISSUE TITLE
Go To Definition causes error (C#/SpecFlow)

### ISSUE THREAD

**Issue by gasparnagy** [cucumber/language-service#70] opened 2022-06-15 06:09 UTC
### 👓 What did you see?

The steps of a scenario are recognized as "defined" (parameter highlighting works), but when I invoke the "Go To Definition" command, it shows a new tab with an error that says "The editor could not be opened due to an unexpected error: File is a directory".

Strangely the header of the tab contains the file name (eg. "MenuStepDefinition.cs"). No additional info on the output.

![image](https://user-images.githubusercontent.com/144701/173754269-ed8cccf2-4805-4fb5-96ec-8660b31eb104.png)

### ✅ What did you expect to see?

Jumps to the step definition.

### 📦 Which tool/library version are you using?

Extension: v1.2.7

### 🔬 How could we reproduce it?

E.g. with the `Menu.feature` of [this](https://github.com/specsolutions/202200607-EuroSTAR-AutomationWithSpecFlow/tree/main/Solutions/F1) repo.

### 📚 Any additional context?

I don't remember having this with the version v1.2.6, but I'm not sure.

**Comment by aslakhellesoy** [comment] 2022-06-16 11:22
I think this might be a duplicate of https://github.com/cucumber/vscode/issues/78

**Comment by gasparnagy** [comment] 2022-06-16 11:53
@aslakhellesoy yeah. let's see. I would keep this open, to be able to verify that both are fixed, because the steps are quite different here.

**Comment by aslakhellesoy** [comment] 2022-07-14 14:39
Fixed in https://github.com/cucumber/language-server/pull/57

**Closed by aslakhellesoy** 2022-07-14 14:39 UTC
