### ISSUE TITLE
Unable to connect to server

### ISSUE THREAD

**Issue by okinlai26** [cucumber/language-service#150] opened 2023-10-06 07:34 UTC
### 👓 What did you see?

I tried to enable the add on within VS code and had 3 error messages (attached) 

### ✅ What did you expect to see?

I expected to see no error messages and the ability to auto complete steps 

### 🔬 How could we reproduce it?

I merely tried to enable the add on 
![CucumberIo](https://github.com/cucumber/language-service/assets/147137633/20da4e64-86ec-4fb5-b717-7d55fdca7706)

See https://stackoverflow.com/help/minimal-reproducible-example

Please outline the steps below:
-->

1. Install '...' version '...'
2. Create a file called '....'
3. Run command '....'
4. See error '....'

### 📚 Any additional context?

----
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

**Comment by kieran-ryan** [comment] 2023-10-08 17:42
Thanks for raising @okinlai26, appears to be a duplicate of #cucumber/vscode/155. There's an incompatibility with the extension and VSCode versions 1.78 - 1.81. Can you update to the latest version of VSCode and check whether that resolves the issue for you. Otherwise would suggest to leave a comment on the linked issue or if you think is a separate issue, we can reopen this ticket. Cheers! 🙌

**Closed** 2023-10-08 17:44 UTC
